apiVersion: v1
kind: Namespace
metadata:
  name: qa-test-runners
  labels:
    app.kubernetes.io/part-of: qa-test-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: selenium-grid
  labels:
    app.kubernetes.io/part-of: qa-test-platform

